# render.yaml

services:
- type: web
  name: your-project-name 
  env: python
  
  # ⭐️ دستور build ساده شده: فقط نصب پکیج‌های پایتون ⭐️
  buildCommand: "pip install -r requirements.txt"
  
  startCommand: "gunicorn app:app"
  
  plan: free 
  
  envVars:
  # IG_USERNAME و IG_PASSWORD برای دانلود استوری اینستاگرام ضروری هستند
  - key: IG_USERNAME
    value: "igdlll" # نام کاربری خود را اینجا وارد کنید (برای استوری‌ها)
  - key: IG_PASSWORD
    value: "Igdlll3456" # رمز عبور خود را اینجا وارد کنید (برای استوری‌ها)
  - key: PYTHON_VERSION
    value: 3.10.12
